spring:
  profiles:
    active: dev

server:
  port: 8080

security:
  jwt:
    key-store: classpath:demo.jks
    key-store-password: P@ssw0rd
    key-pair-alias: demo
    key-pair-password: P@ssw0rd

