spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: demo_usr
    password: demo_usr
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

