spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: demo_usr
    password: demo_usr
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    locations: classpath:/db/migration, classpath:/db/test_data

logging:
  config: classpath:logback-dev.xml

security:
  jwt:
    key-store: classpath:demo.jks
    key-store-password: P@ssw0rd
    key-pair-alias: demo
    key-pair-password: P@ssw0rd

